apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: alertmgr-conf-policy
  namespace: open-cluster-management-observability
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: alertmgr-conf-policy
        spec:
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - open-cluster-management-observability
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: alertmanager-config
                  namespace: open-cluster-management-observability
                stringData:
                  alertmanager.yaml: |
                    global:
                      slack_api_url:  '{{fromSecret "open-cluster-management" "kcp-sgs-pipelines-secrets-config" "defaultSlackAPI" | base64dec }}'

                    route:
                      receiver: default-receiver
                      group_by: ['alertname', 'cluster', 'namespace']
                      group_wait: 30s
                      group_interval: 5m
                      repeat_interval: 4h
                      routes:
                        - receiver: mute-alerts
                          matchers:
                            - alertname =~ "AlertmanagerReceiversNotConfigured"
                        - receiver: ignored-kube-state-metrics-alert
                          matchers:
                            # kube-state-metrics issue: https://issues.redhat.com/browse/AAP-4197
                            - alertname = "KubeStateMetricsListErrors"
                            - severity = "critical"
                        - receiver: default-receiver
                          matchers:
                            - severity =~ "warning|critical"
                          continue: true
                        - receiver: to-github
                          group_by: ['...']
                          matchers:
                            - alertname =~ ".*"
                          continue: true
                        - receiver: pagerduty-acm-kcp-critical
                          matchers:
                            - severity = "critical"
                            - team = "acm-sre"
                        - receiver: pagerduty-acm-kcp-warning
                          matchers:
                            - severity = "warning"
                            - team = "acm-sre"

                    receivers:
                      # remove all ignored-xxx receiver when we fixed the alert issue
                      - name: ignored-kube-state-metrics-alert
                      - name: ignored-cert-manager-argo-alert
                      - name: mute-alerts
                      - name: to-github
                        webhook_configs:
                        - url: "http://alertmanager-to-github.alertmanager-to-github/v1/webhook?owner=stolostron&repo=incident-backlog&labels=auto-created,kcp,dev"
                      - name: default-receiver
                        slack_configs:
                        - channel: team-acm-sgs-prod-alerts
                          actions:
                            - name: "links"
                              text: "ACM"
                              type: "button"
                              url:  https://{{ (lookup "route.openshift.io/v1" "Route" "open-cluster-management" "multicloud-console").spec.host }}
                            - name: "links"
                              text: "Grafana :grafana:"
                              type: "button"
                              url: https://{{fromSecret "openshift-gitops" "console-url" "ACM_CONSOLE_URL" | base64dec}}{{`/grafana/explore?orgId=1&left=["now-1h","now","Observatorium",{"expr":"ALERTS{alertname=\"{{ .CommonLabels.alertname }}\",cluster=\"{{ .CommonLabels.cluster }}\"}","context":"explore"},{"mode":"Metrics"},{"ui":[true,true,true,"none"]}]`}}'
                          footer: |
                            "{{`{{ .CommonLabels.cluster }}`}}"
                          mrkdwn_in:
                            - text
                            - actions
                          text: |-
                            "{{`{{ range .Alerts }}`}}"
                              :failed: - *Alerts:* "{{`{{ .Annotations.summary }}`}}"
                              :green_book: - *Description:* "{{`{{ .Annotations.description }}`}}"
                              :clipboard: - *Details:*
                              "{{`{{ range .Labels.SortedPairs }} â€¢ *{{ .Name }}:* {{ .Value }} {{ printf "\n" }} {{ end }}`}}"
                            "{{`{{ end }}`}}"
                          title: "{{`[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }} ({{ .CommonLabels.severity }})`}}"
                          title_link: http://{{fromSecret "openshift-gitops" "console-url" "ALERTMANAGER_URL" | base64dec}}/#/alerts
                      - name: 'pagerduty-acm-kcp-critical'
                        pagerduty_configs:
                        - service_key: '{{fromSecret "open-cluster-management" "kcp-sgs-pipelines-secrets-config" "pagerdutyServiceKey" | base64dec }}'
                      - name: 'pagerduty-acm-kcp-warning'
                        pagerduty_configs:
                        - service_key: '{{fromSecret "open-cluster-management" "kcp-sgs-pipelines-secrets-config" "pagerdutyServiceKey" | base64dec }}'
          remediationAction: inform
          severity: low
  remediationAction: enforce
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-alertmgr-conf-policy
  namespace: open-cluster-management-observability
  annotations:
    argocd.argoproj.io/sync-wave: "1"
placementRef:
  name: placement-alertmgr-conf-policy
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: alertmgr-conf-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-alertmgr-conf-policy
  namespace: open-cluster-management-observability
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - local-cluster
